sudo: required
language: bash
dist: xential

jobs:
  include:
  - arch: amd64
  include:
  - arch: arm64

script:
  - apt install libavformat-dev libavcodec-dev libswresample-dev libswscale-dev libavutil-dev libsdl1.2-dev ffmpeg \
    && mkdir build && cd build && cmake .. && make -j 8
after_script:
  - ls
