sudo: required
language: bash
dist: xential

addons:
  apt:
    packages:
      - cmake
      - libavformat-dev 
      - libavcodec-dev 
      - libswresample-dev 
      - libswscale-dev 
      - libavutil-dev 
      - libsdl1.2-dev 
      - libavdevice-dev
      - libavfilter-dev
      - ffmpeg

jobs:
  include:
  - arch: amd64
  - arch: arm64

script:
  - mkdir build && cd build && cmake .. && make -j 8
after_script:
  - ls
